# Create the tracked operator guide only when it is missing.
#
# The guide is meant to become repo- and operator-specific over time, so this
# function must never regenerate or "fix" an existing file. That avoids turning
# useful human notes into generated churn.
ensure_operator_guide() {
  [[ "$CODEX_OPERATOR_GUIDE_BOOTSTRAP" == "1" ]] || return 0

  local guide_path guide_dir tmp_file
  guide_path="$(resolved_operator_guide_path)"
  if [[ -z "$guide_path" ]]; then
    log_line "WARN" "operator_guide.bootstrap_skip reason=empty_path"
    return 0
  fi
  if [[ "$guide_path" != "$ROOT_DIR/"* || "$guide_path" == "$ROOT_DIR" || "$guide_path" == "$ROOT_DIR/" ]]; then
    log_line "WARN" "operator_guide.bootstrap_skip reason=non_repo_path path=$guide_path"
    return 0
  fi
  if [[ -e "$guide_path" || -L "$guide_path" ]]; then
    check_existing_operator_guide "$guide_path"
    return 0
  fi

  if operator_guide_is_ignored "$guide_path"; then
    log_line "INFO" "operator_guide.local_missing path=$guide_path current_version=$UPKEEPER_VERSION action=ignored_no_bootstrap"
    return 0
  fi

  guide_dir="$(dirname -- "$guide_path")"
  if ! mkdir -p "$guide_dir"; then
    log_line "WARN" "operator_guide.bootstrap_skip reason=directory_create_failed path=$guide_dir"
    return 0
  fi
  if ! tmp_file="$(mktemp "$guide_dir/.upkeeper-guide.XXXXXX")"; then
    log_line "WARN" "operator_guide.bootstrap_skip reason=temp_create_failed path=$guide_dir"
    return 0
  fi
  if ! {
    printf '# %s\n\n' "$SCRIPT_NAME"
    printf '> Bootstrap-generated by `%s` because `%s` was missing.\n\n' "$SCRIPT_NAME" "$guide_path"
    printf 'Keep this file as the repo-local living operator guide. The wrapper only creates it when missing; it does not overwrite future edits.\n\n'
    printf '## Script Help Snapshot\n\n'
    printf '```text\n'
    show_help
    printf '```\n\n'
    printf '## Repo-Local Living Notes\n\n'
    printf -- '- Record local relaunch conventions, recurring incident lessons, and environment-specific guardrail decisions here.\n'
    printf -- '- Keep transient run logs and generated postmortems under `runtime/`; promote only durable operating rules into this guide.\n'
  } >"$tmp_file"; then
    rm -f "$tmp_file"
    log_line "WARN" "operator_guide.bootstrap_skip reason=temp_write_failed path=$guide_dir"
    return 0
  fi

  # Install by hard link so a guide created after the initial existence check is
  # never overwritten by bootstrap output.
  if ! ln "$tmp_file" "$guide_path" 2>/dev/null; then
    rm -f "$tmp_file"
    if [[ -e "$guide_path" || -L "$guide_path" ]]; then
      check_existing_operator_guide "$guide_path"
      return 0
    fi
    log_line "WARN" "operator_guide.bootstrap_skip reason=install_failed path=$guide_path"
    return 0
  fi
  rm -f "$tmp_file" || log_line "WARN" "operator_guide.temp_cleanup_failed path=$tmp_file"
  log_line "INFO" "operator_guide.bootstrap path=$guide_path source=show_help"
}
