#!/usr/bin/env bash
set -euo pipefail

# One quota-respecting all-pass Upkeeper cycle against the current selector.

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

UPKEEPER_CMD="${UPKEEPER_CMD:-./Upkeeper}"
UPKEEPER_TEST_MODEL="${UPKEEPER_TEST_MODEL:-gpt-5.5}"
UPKEEPER_TEST_EFFORT="${UPKEEPER_TEST_EFFORT:-xhigh}"
UPKEEPER_TEST_5H_STOP_PERCENT="${UPKEEPER_TEST_5H_STOP_PERCENT:-5}"
UPKEEPER_TEST_WEEK_STOP_PERCENT="${UPKEEPER_TEST_WEEK_STOP_PERCENT:-15}"
UPKEEPER_TEST_TERMINAL_VERBOSITY="${UPKEEPER_TEST_TERMINAL_VERBOSITY:-basic}"

CODEX_MODEL="$UPKEEPER_TEST_MODEL" \
  CODEX_REASONING_EFFORT="$UPKEEPER_TEST_EFFORT" \
  CODEX_5H_STOP_PERCENT="$UPKEEPER_TEST_5H_STOP_PERCENT" \
  CODEX_WEEK_STOP_PERCENT="$UPKEEPER_TEST_WEEK_STOP_PERCENT" \
  CODEX_TERMINAL_VERBOSITY="$UPKEEPER_TEST_TERMINAL_VERBOSITY" \
  "$UPKEEPER_CMD" --prompt-pass=all --review-modules=p24,p25,p26,p27,p28 "$@"
