#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: tools/upkeeper_precontact_bootstrap.sh [--identity-file=PATH] [--local-env-file=PATH]

Bootstrap machine-local encrypted pre-contact backup settings for Upkeeper.

This command creates an age identity when needed, derives the public recipient,
and stores only UPKEEPER_PRECONTACT_BACKUP_AGE_RECIPIENT in a trusted local env
file. The private identity remains machine-local and is not written into the
env file.
EOF
}

fail() {
  printf 'upkeeper_precontact_bootstrap: ERROR: %s\n' "$*" >&2
  exit 2
}

require_command() {
  local name="$1"
  command -v "$name" >/dev/null 2>&1 || fail "required command missing: $name"
}

assert_no_symlink_path_components() {
  local raw_path="$1"
  local absolute_path="$2"
  local remainder component segment

  [[ "$absolute_path" == /* ]] || fail "$raw_path did not resolve to an absolute path"
  remainder="${absolute_path#/}"
  component="/"
  while [[ -n "$remainder" ]]; do
    segment="${remainder%%/*}"
    if [[ "$component" == "/" ]]; then
      component="/$segment"
    else
      component="$component/$segment"
    fi
    [[ -L "$component" ]] && fail "path must not include symlink components: $component"
    if [[ "$remainder" == */* ]]; then
      remainder="${remainder#*/}"
    else
      remainder=""
    fi
  done
}

resolve_abs_path() {
  python3 - "$1" <<'PY'
from pathlib import Path
import sys

print(Path(sys.argv[1]).expanduser().resolve(strict=False))
PY
}

IDENTITY_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/age/upkeeper.txt"
LOCAL_ENV_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/upkeeper/local.env"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --identity-file=*)
      IDENTITY_FILE="${1#*=}"
      ;;
    --identity-file)
      fail "use --identity-file=PATH"
      ;;
    --local-env-file=*)
      LOCAL_ENV_FILE="${1#*=}"
      ;;
    --local-env-file)
      fail "use --local-env-file=PATH"
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      fail "unknown argument: $1"
      ;;
  esac
  shift
done

require_command age
require_command age-keygen

IDENTITY_FILE="$(resolve_abs_path "$IDENTITY_FILE")"
LOCAL_ENV_FILE="$(resolve_abs_path "$LOCAL_ENV_FILE")"
IDENTITY_DIR="$(dirname -- "$IDENTITY_FILE")"
LOCAL_ENV_DIR="$(dirname -- "$LOCAL_ENV_FILE")"

assert_no_symlink_path_components "identity path" "$IDENTITY_FILE"
assert_no_symlink_path_components "local env path" "$LOCAL_ENV_FILE"

mkdir -p -- "$IDENTITY_DIR" "$LOCAL_ENV_DIR"
chmod 700 "$IDENTITY_DIR" "$LOCAL_ENV_DIR" 2>/dev/null || true

identity_created=0
if [[ -e "$IDENTITY_FILE" ]]; then
  [[ -f "$IDENTITY_FILE" ]] || fail "identity path is not a regular file: $IDENTITY_FILE"
  [[ ! -L "$IDENTITY_FILE" ]] || fail "identity path must not be a symlink: $IDENTITY_FILE"
else
  age-keygen -o "$IDENTITY_FILE" >/dev/null
  identity_created=1
fi
chmod 600 "$IDENTITY_FILE" 2>/dev/null || true

recipient="$(age-keygen -y "$IDENTITY_FILE" 2>/dev/null)" || fail "failed to derive age recipient from identity"
[[ -n "$recipient" ]] || fail "derived age recipient was empty"

python3 - "$LOCAL_ENV_FILE" "$recipient" <<'PY'
from pathlib import Path
import os
import re
import sys

path = Path(sys.argv[1])
recipient = sys.argv[2]
line = f"export UPKEEPER_PRECONTACT_BACKUP_AGE_RECIPIENT={recipient}"
header = [
    "# Upkeeper machine-local environment.",
    "# Generated by tools/upkeeper_precontact_bootstrap.sh.",
    "# Stores only the public age recipient; keep the private identity separate.",
]

if path.exists():
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
else:
    lines = []

pattern = re.compile(r"^\s*(?:export\s+)?UPKEEPER_PRECONTACT_BACKUP_AGE_RECIPIENT=")
replaced = False
new_lines = []
for existing in lines:
    if pattern.match(existing):
        if not replaced:
            new_lines.append(line)
            replaced = True
        continue
    new_lines.append(existing)

if not replaced:
    if new_lines and new_lines[-1].strip():
        new_lines.append("")
    if not any(existing.startswith("# Upkeeper machine-local environment.") for existing in new_lines):
        new_lines.extend(header)
    new_lines.append(line)

payload = "\n".join(new_lines).rstrip() + "\n"
tmp = path.with_name(f"{path.name}.tmp.{os.getpid()}")
with open(tmp, "w", encoding="utf-8") as handle:
    handle.write(payload)
os.chmod(tmp, 0o600)
os.replace(tmp, path)
os.chmod(path, 0o600)
PY

printf 'upkeeper_precontact_bootstrap: age identity %s: %s\n' \
  "$([[ "$identity_created" == "1" ]] && printf 'created' || printf 'reused')" \
  "$IDENTITY_FILE"
printf 'upkeeper_precontact_bootstrap: wrote public recipient to %s\n' "$LOCAL_ENV_FILE"
printf 'upkeeper_precontact_bootstrap: only the public recipient was stored; keep %s machine-local and use it only for manual restore\n' "$IDENTITY_FILE"
printf 'upkeeper_precontact_bootstrap: rerun your Upkeeper launcher after this command exits cleanly\n'
